import React, { useState, useEffect } from 'react';

export default function ShiftHandoff({ patientId, token }) {
  const [handoff, setHandoff] = useState(null);
  const [loading, setLoading] = useState(false);

  const generateHandoff = () => {
    setLoading(true);
    fetch(`/api/clinical/handoff/${patientId}`, {
      headers: { Authorization: `Bearer ${token}` }
    })
      .then(res => res.json())
      .then(data => {
        setHandoff(data);
        setLoading(false);
      })
      .catch(console.error);
  };

  return (
    <div className="shift-handoff" style={{ margin: '20px 0', padding: '15px', backgroundColor: '#e9ecef', borderRadius: '8px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <h3 style={{ margin: 0 }}>AI Shift Handoff Summary</h3>
        <button onClick={generateHandoff} disabled={loading} style={{ padding: '8px 16px' }}>
          {loading ? 'Generating...' : 'Generate Handoff'}
        </button>
      </div>
      
      {handoff && (
        <div style={{ marginTop: '15px', padding: '15px', backgroundColor: 'white', borderRadius: '4px' }}>
          <div style={{ padding: '10px', backgroundColor: '#fff3cd', color: '#856404', borderRadius: '4px', marginBottom: '15px' }}>
            <strong>⚠️ CLINICIAN REVIEW REQUIRED:</strong> This summary is generated by AI based on verified system data. It is for decision support only and does not constitute a diagnosis or medical directive.
          </div>
          <div style={{ whiteSpace: 'pre-wrap' }}>{handoff.summary}</div>
          <div style={{ marginTop: '10px', fontSize: '0.85em', color: '#6c757d' }}>
            Source: {handoff.source}
          </div>
        </div>
      )}
    </div>
  );
}
